-- Weekly Outfit Planner Migration
-- Adds weekly_plans table and expands clothes.type enum

-- ============================================================================
-- 1. Expand clothes.type enum to include more categories
-- ============================================================================

-- Drop existing constraint if it exists
ALTER TABLE clothes DROP CONSTRAINT IF EXISTS clothes_type_check;

-- Add new constraint with expanded types
ALTER TABLE clothes ADD CONSTRAINT clothes_type_check
  CHECK (type IN ('top', 'bottom', 'shoes', 'accessories', 'outerwear', 'hat', 'layer'));

-- ============================================================================
-- 2. Create weekly_plans table
-- ============================================================================

CREATE TABLE IF NOT EXISTS weekly_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,  -- Monday of the week
  outfits JSONB NOT NULL,    -- Array of 7 day objects
  weather_data JSONB,        -- Cached 7-day weather forecast
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Ensure one plan per user per week
  CONSTRAINT weekly_plans_unique_user_week UNIQUE(user_id, week_start)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_weekly_plans_user_id ON weekly_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_weekly_plans_week_start ON weekly_plans(week_start DESC);
CREATE INDEX IF NOT EXISTS idx_weekly_plans_user_week ON weekly_plans(user_id, week_start);

-- Row Level Security
ALTER TABLE weekly_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own weekly plans"
  ON weekly_plans FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own weekly plans"
  ON weekly_plans FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own weekly plans"
  ON weekly_plans FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own weekly plans"
  ON weekly_plans FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================================================
-- 3. Function to update updated_at timestamp
-- ============================================================================

CREATE OR REPLACE FUNCTION update_weekly_plans_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
DROP TRIGGER IF EXISTS trigger_weekly_plans_updated_at ON weekly_plans;
CREATE TRIGGER trigger_weekly_plans_updated_at
  BEFORE UPDATE ON weekly_plans
  FOR EACH ROW
  EXECUTE FUNCTION update_weekly_plans_updated_at();

-- ============================================================================
-- 4. Table comments
-- ============================================================================

COMMENT ON TABLE weekly_plans IS 'Stores 7-day outfit plans generated by AI';
COMMENT ON COLUMN weekly_plans.week_start IS 'Monday of the week (ISO 8601 week start)';
COMMENT ON COLUMN weekly_plans.outfits IS 'JSONB array of 7 day objects with outfit data';
COMMENT ON COLUMN weekly_plans.weather_data IS 'Cached weather forecast for the week';

-- ============================================================================
-- 5. Example JSONB structure (for documentation)
-- ============================================================================

/*
outfits JSONB structure:
[
  {
    "day": "monday",
    "date": "2025-12-08",
    "item_ids": ["uuid1", "uuid2", "uuid3"],
    "hero_item_id": "uuid1",
    "ai_insight": {
      "reason": "This outfit matches your casual streetwear aesthetic...",
      "occasion": "Casual Day Out",
      "vibe": "Minimal Streetwear"
    },
    "suggested_accessory_ids": ["uuid5", "uuid6"]
  },
  ... (6 more days)
]

weather_data JSONB structure:
[
  {
    "date": "2025-12-08",
    "temp_high": 65,
    "temp_low": 50,
    "condition": "Partly Cloudy",
    "icon": "partly_cloudy"
  },
  ... (6 more days)
]
*/
